---

utilities_list:
  - nmon
  - tree
  - snap
  - git
  - ansible
  - python3
  - python3-pip

laptop_utils:
- laptop-mode-tools
  - powertop
  - cpufrequtils

games_list:
  - 0ad
  - frozen-bubble
  - hedgewars
  - lbreakout2
  - pingus
  - steam-installer
  - supertuxkart

web_list:

snap_list:
 - "pycharm --classic"
