---
- hosts: localhost
  pre_tasks:
    - name: APT DIST-UPGRADE
      apt:
        update_cache: yes
        upgrade: dist
      become: yes
      tags:
        - always

    - name: INSTALL PACKAGES
      apt:
        name: "{{ item }}"
        state: latest
      become: yes
      with_items: "{{ packages_list }}"
      tags:
        - always
 
    - name: SNAP -- REFRESH SNAPS
      command: snap refresh
      become: yes
      tags:
        - always

  tasks:
    - name: INSTALL GAMES
      apt:
        name: "{{ item }}"
        state: latest
      become: yes
      with_items: "{{ games_list }}"
      tags:
        - games

    - name: INSTALL LAPTOP UTILITIES
      apt:
        name: "{{ item }}"
        state: latest
      become: yes
      with_items: "{{ laptop_utils }}"
      tags:
        - laptop

  post_tasks:
    - name: SNAPS -- REMOVE DISABLED SNAPS
      shell: snap list --all | grep disabled | awk '{system("sudo snap remove --revision " $3 " " $1)}'
      become: yes
      tags:
        - always

    - name: APT -- AUTOREMOVE AND AUTOCLEAN
      apt:
        autoremove: yes
        autoclean: yes
      tags:
        - always

  roles:
  - role: web
    tags:
      - web
      - standard_install

  - role: java
    tags:
      - java
      - standard_install

  - role: vmware
    tags:
      - vmware
      - standard_install

  - role: snaps
    tags:
      - snaps
      - standard_install
      - web
      - games
