---
- name: GOOGLE CHROME -- ADD KEY
  apt_key:
    url: "https://dl-ssl.google.com/linux/linux_signing_key.pub"
    state: present

- name: GOOGLE CHROME -- ADD REPO
  apt_repository:
    repo: "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main"
    filename: "google-chrome"
    state: present
    update_cache: yes

- name: GOOGLE CHROME -- INSTALL CHROME
  apt:
    name: google-chrome-stable
    state: latest

- name: OPERA -- ADD KEY
  apt_key: 
    url:  "http://deb.opera.com/archive.key"
    state=present

- name: OPERA -- ADD REPO
  apt_repository:
    repo: "deb http://deb.opera.com/opera/ stable non-free"
    state=present

- name: INSTALL OPERA
  apt:
    name= opera
    state=latest

- name: INSTALL WEB
  apt:
    name: "{{ item }}"
    state: present
  become: yes
  with_items: "{{ web_list }}"

